name: Heybox Auto Sign

on:
  schedule:
    # 北京时间每天早上 8 点自动运行 (UTC 0:00)
    - cron: '0 0 * * *'
  workflow_dispatch: # 允许手动点击运行

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install got@^11.8.6

      - name: Run sign-in script
        env:
          heybox_ck: ${{ secrets.heybox_ck }}
        run: node heybox_sign.js
